### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#120]
Following code will cause segmentation fault when running with `tpl --ns`.

```
foo('^', A, B^C) :-
        write(A), nl.
```

Backtrace:

```
Core was generated by `tpl --ns foo.pl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000405a36 in term_next (n=0x21) at src/bifs.h:268
268     inline static node *term_next(node *n) { return NLIST_NEXT(n); }
(gdb) bt
#0  0x0000000000405a36 in term_next (n=0x21) at src/bifs.h:268
#1  0x0000000000405e1c in term_heapclean (n=0x48ebd60) at src/trealla.c:109
#2  0x0000000000405bc6 in term_heapcheck (n=0x48ebd60) at src/bifs.h:293
#3  0x0000000000405e2c in term_heapclean (n=0x48eb780) at src/trealla.c:110
#4  0x0000000000405bc6 in term_heapcheck (n=0x48eb780) at src/bifs.h:293
#5  0x0000000000405e2c in term_heapclean (n=0x48ebe00) at src/trealla.c:110
#6  0x0000000000405bc6 in term_heapcheck (n=0x48ebe00) at src/bifs.h:293
#7  0x0000000000406f8e in rule_done (p=0x48e8530) at src/trealla.c:445
#8  0x000000000044275e in sl_done (d=0x48df060, deleter=0x406f49 <rule_done>) at src/skiplist.c:311
#9  0x0000000000407201 in db_done (self=0x48df040) at src/trealla.c:500
#10 0x000000000040abc1 in trealla_destroy (self=0x48df010) at src/trealla.c:1616
#11 0x00000000004058d9 in main (ac=3, av=0x7ffe7ab4d2e8) at tpl.c:481
(gdb) 
```

**Comment by dram** [comment]
Add a test case in trealla-tests repo.

This test is simplified from code of [?-Prolog](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/compile.pl#compile.pl-277).

**Comment by dram** [comment]
Thanks!
