### ISSUE TITLE
Segmentation fault when consulting source from stdin which has `include/1`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#122]
For following script, a segmentation fault will be triggered:

```
!/bin/sh

tpl -q --consult <<EOF

:- include('non-exists-file.pro').

EOF
```

Backtrace:

```
Core was generated by `tpl -q --consult'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
296     ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:296
#1  0x000000000040d17a in dir_include (l=0x7ffe1631bf80, n=0x57e5c70) at src/parser.c:914
#2  0x000000000040d2d5 in directive (l=0x7ffe1631bf80, n=0x57e5c20) at src/parser.c:943
#3  0x00000000004103d1 in lexer_finalize (self=0x7ffe1631bf80) at src/parser.c:1944
#4  0x00000000004122e1 in lexer_parse (self=0x7ffe1631bf80, term=0x57da450, src=0x57e3b92 "", line=0x7ffe1631bf38) at src/parser.c:2370
#5  0x0000000000412561 in lexer_consult_fp (self=0x7ffe1631bf80, fp=0x7f283cb924e0 <_IO_2_1_stdin_>) at src/parser.c:2423
#6  0x0000000000409255 in trealla_consult_fp (self=0x57d7010, fp=0x7f283cb924e0 <_IO_2_1_stdin_>) at src/trealla.c:1250
#7  0x0000000000404fb2 in main (ac=3, av=0x7ffe1631cd08) at tpl.c:370
(gdb) 
```

**Comment by dram** [comment]
Fix confirmed, thanks.
