### ISSUE TITLE
Segmentation fault when run `tpl` with `--trace`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#126]
For following code, Trealla will be crash with segmentation fault if run `tpl` with `--trace`:

```
:- initialization(main).

foo(Args) :- sys:split('', ' ', Args).

main :- foo(Args), halt.
```

Backtrace:

```
Core was generated by `tpl --trace foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043b3ca in get_arg (q=0x2754ed0, term=0x0, frame=2) at src/bifs.h:208
208             if (!is_var(term)) {
(gdb) bt
#0  0x000000000043b3ca in get_arg (q=0x2754ed0, term=0x0, frame=2) at src/bifs.h:208
#1  0x000000000043ba74 in sprint2_list (depth=6, dstbuf=0x7fff39b29478, bufsize=0x7fff39b29480, _dst=0x7fff39b27168,
    pl=0x2746010, q=0x2754ed0, n=0x2749450, listing=1) at src/print.c:163
#2  0x000000000043d3d2 in sprint2_term (depth=5, dstbuf=0x7fff39b29478, bufsize=0x7fff39b29480, _dst=0x7fff39b28250,
    pl=0x2746010, q=0x2754ed0, _n=0x2749450, listing=1) at src/print.c:379
#3  0x000000000043ce2a in sprint2_compound (depth=4, dstbuf=0x7fff39b29478, bufsize=0x7fff39b29480, _dst=0x7fff39b29368,
    pl=0x2746010, q=0x2754ed0, n=0x2757400, listing=1) at src/print.c:319
#4  0x000000000043d43d in sprint2_term (depth=1, dstbuf=0x7fff39b29478, bufsize=0x7fff39b29480, _dst=0x7fff39b29470,
    pl=0x2746010, q=0x2754ed0, _n=0x27573b0, listing=1) at src/print.c:381
#5  0x000000000043e6de in term_sprint2 (dstbuf=0x7fff39b29478, bufsize=0x7fff39b29480, dst=0x7fff39b29470, pl=0x2746010,
    q=0x2754ed0, n=0x27573b0, listing=1) at src/print.c:537
#6  0x00000000004080ad in trace (q=0x2754ed0, fail=0, leave=1) at src/trealla.c:886
#7  0x0000000000439bf0 in run_me (q=0x2754ed0) at src/jela.c:485
#8  0x00000000004081c4 in query_run (self=0x2754ed0) at src/trealla.c:909
#9  0x0000000000409887 in trealla_run_query (self=0x2746010, src=0x2751460 "main.") at src/trealla.c:1392
#10 0x000000000040947b in trealla_consult_file (self=0x2746010, filename=0x7fff39b2a816 "foo.pro") at src/trealla.c:1293
#11 0x0000000000404f5c in main (ac=3, av=0x7fff39b2a2b8) at tpl.c:364
(gdb)
```

**Comment by dram** [comment]
Thanks.
