### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#128]
For following code, instead of infinite loop, Trealla crash with segmentation fault quickly:

```
:- initialization(main).

main :-
        loop(_).

loop(X) :-
        write(loop), nl,
        foo(_),
        loop(X).

foo(_).
```

Output:

```
% tpl foo.pro
loop
loop
loop
Segmentation fault (core dumped)
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043a40c in unify_compound (q=0x1308ed0, term1=0x130ba70, context1=2, term2=0x130b4e0, context2=5)
    at src/jela.c:607
607                     if (is_compound(tmp1) && is_compound(tmp2))
(gdb) bt
#0  0x000000000043a40c in unify_compound (q=0x1308ed0, term1=0x130ba70, context1=2, term2=0x130b4e0, context2=5)
    at src/jela.c:607
#1  0x000000000043a518 in unify (q=0x1308ed0, term1=0x130ba20, context1=2, term2=0x130b490, context2=5) at src/jela.c:626
#2  0x000000000043a9e4 in match (q=0x1308ed0) at src/jela.c:735
#3  0x00000000004399bb in call (q=0x1308ed0) at src/jela.c:427
#4  0x0000000000439b5d in run_me (q=0x1308ed0) at src/jela.c:469
#5  0x00000000004081c4 in query_run (self=0x1308ed0) at src/trealla.c:909
#6  0x0000000000409887 in trealla_run_query (self=0x12fa010, src=0x1305460 "main.") at src/trealla.c:1392
#7  0x000000000040947b in trealla_consult_file (self=0x12fa010, filename=0x7ffd5732b818 "foo.pro") at src/trealla.c:1293
#8  0x0000000000404f5c in main (ac=2, av=0x7ffd57329a38) at tpl.c:364
(gdb)
```

**Comment by dram** [comment]
Add a slightly different test to trealla-tests repo, which has a finite loop.

**Comment by infradig** [comment]
It's to do with the default -O3 level optimization
(tail-recursion-elimination). Add -O2 and it works.

**Comment by infradig** [comment]
And also the var-var binding. Works if the foo/1 call grounds.

**Comment by dram** [comment]
Thanks, fix confirmed.
