### ISSUE TITLE
Define and call read/3 cause segmentation fault

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#137]
Following code will cause segmentation fault for Trealla.

```
:- initialization(main).

read(_, _, _).

main :- read(_, _, _), halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000043a876 in call (q=0x1fa8ec0) at src/jela.c:423
#2  0x000000000043aa4c in run_me (q=0x1fa8ec0) at src/jela.c:473
#3  0x0000000000408215 in query_run (self=0x1fa8ec0) at src/trealla.c:913
#4  0x000000000040988f in trealla_run_query (self=0x1f9a010, src=0x1fa5450 "main.") at src/trealla.c:1395
#5  0x00000000004094ca in trealla_consult_file (self=0x1f9a010, filename=0x7ffea41aa814 "foo.pro") at src/trealla.c:1299
#6  0x0000000000404f5c in main (ac=2, av=0x7ffea41a9568) at tpl.c:364
```

**Comment by dram** [comment]
Thanks, fix confirmed.
