### ISSUE TITLE
 Assertion failed for (=..)/2

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#141]
Following code will trigger an assertion failed error:

```
:- initialization(main).

main :- T =.. [_], halt.
```

Output:

```
% tpl foo.pro
tpl: src/list.c:29: list_push_back: Assertion `l && entry' failed.
Aborted (core dumped)
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff291d94067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ff291d94067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ff291d95448 in __GI_abort () at abort.c:89
#2  0x00007ff291d8d266 in __assert_fail_base (fmt=0x7ff291ec5f18 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x479cdb "l && entry", file=file@entry=0x479cd0 "src/list.c", line=line@entry=29,
    function=function@entry=0x479d30 <__PRETTY_FUNCTION__.2250> "list_push_back") at assert.c:92
#3  0x00007ff291d8d312 in __GI___assert_fail (assertion=0x479cdb "l && entry", file=0x479cd0 "src/list.c", line=29,
    function=0x479d30 <__PRETTY_FUNCTION__.2250> "list_push_back") at assert.c:101
#4  0x000000000043c927 in list_push_back (l=0x1309600, entry=0x0) at src/list.c:29
#5  0x000000000041311c in term_append (s=0x13095f0, n=0x0) at src/bifs.h:279
#6  0x0000000000423598 in bif_iso_univ (q=0x1307090) at src/bifs_iso.c:3478
#7  0x000000000043b578 in call (q=0x1307090) at src/jela.c:423
#8  0x000000000043b74e in run_me (q=0x1307090) at src/jela.c:473
#9  0x00000000004082c9 in query_run (self=0x1307090) at src/trealla.c:918
#10 0x000000000040995e in trealla_run_query (self=0x12f8010, src=0x1305990 "main.") at src/trealla.c:1405
#11 0x0000000000409596 in trealla_consult_file (self=0x12f8010, filename=0x7ffe8d31a824 "foo.pro") at src/trealla.c:1308
#12 0x0000000000404f9b in main (ac=2, av=0x7ffe8d31a178) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
