### ISSUE TITLE
Unification error

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#143]
In following code, `A` will failed to unify in Trealla:

```
:- initialization(main).

foo([:-(A)]) :- write(A), nl.

main :- foo([:-(bar)]), halt.
```

It works in GProlog, SWI and Yap.

**Comment by dram** [comment]
BTW, this test will trigger a segmentation fault when running with trace enabled:

```
% tpl --trace issues/0143.pro
Call: ?- main
Call: main
Exit: main
Segmentation fault (core dumped)
```

Backtrace:

```
Core was generated by `tpl --trace issues/0143.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000440e4e in get_arg (q=0x2bed040, term=0x0, frame=1) at src/bifs.h:209
209             if (!is_var(term)) {
(gdb) bt
#0  0x0000000000440e4e in get_arg (q=0x2bed040, term=0x0, frame=1) at src/bifs.h:209
#1  0x0000000000441516 in sprint2_list (depth=4, dstbuf=0x7fffbfe36118, bufsize=0x7fffbfe36110, _dst=0x7fffbfe32de0,
    pl=0x2bde010, q=0x2bed040, n=0x2bf0a30, listing=1) at src/print.c:163
#2  0x00000000004430f0 in sprint2_term (depth=3, dstbuf=0x7fffbfe36118, bufsize=0x7fffbfe36110, _dst=0x7fffbfe33ee8,
    pl=0x2bde010, q=0x2bed040, _n=0x2bf0a30, listing=1) at src/print.c:379
#3  0x0000000000442a8d in sprint2_compound (depth=2, dstbuf=0x7fffbfe36118, bufsize=0x7fffbfe36110, _dst=0x7fffbfe34ff0,
    pl=0x2bde010, q=0x2bed040, n=0x2bf0a30, listing=1) at src/print.c:319
#4  0x0000000000443161 in sprint2_term (depth=1, dstbuf=0x7fffbfe36118, bufsize=0x7fffbfe36110, _dst=0x7fffbfe36120,
    pl=0x2bde010, q=0x2bed040, _n=0x2bf09e0, listing=1) at src/print.c:381
#5  0x00000000004445e6 in term_sprint2 (dstbuf=0x7fffbfe36118, bufsize=0x7fffbfe36110, dst=0x7fffbfe36120, pl=0x2bde010,
    q=0x2bed040, n=0x2bf09e0, listing=1) at src/print.c:537
#6  0x00000000004089d2 in trace (q=0x2bed040, fail=0, leave=0) at src/trealla.c:895
#7  0x000000000043f2d2 in call (q=0x2bed040) at src/jela.c:418
#8  0x000000000043f4e1 in run_me (q=0x2bed040) at src/jela.c:473
#9  0x0000000000408b03 in query_run (self=0x2bed040) at src/trealla.c:918
#10 0x000000000040a345 in trealla_run_query (self=0x2bde010, src=0x2bec340 "main.") at src/trealla.c:1405
#11 0x0000000000409ee1 in trealla_consult_file (self=0x2bde010, filename=0x7fffbfe37807 "issues/0143.pro")
    at src/trealla.c:1308
#12 0x000000000040525a in main (ac=3, av=0x7fffbfe37088) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
