### ISSUE TITLE
Segmentation fault for atom_concat/3

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#144]
Following code will cause segmentation fault:

```
:- initialization(main).

main :- atom_concat('a', '.', A), write(A), nl, halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:140
140     ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:140
#1  0x0000000000416d09 in bif_iso_atom_concat (q=0x2289fd0) at src/bifs_iso.c:776
#2  0x000000000043bcf3 in call (q=0x2289fd0) at src/jela.c:423
#3  0x000000000043bec9 in run_me (q=0x2289fd0) at src/jela.c:473
#4  0x00000000004082c9 in query_run (self=0x2289fd0) at src/trealla.c:918
#5  0x0000000000409973 in trealla_run_query (self=0x227b010, src=0x2288690 "main.") at src/trealla.c:1405
#6  0x00000000004095a2 in trealla_consult_file (self=0x227b010, filename=0x7ffcbbf12828 "foo.pro") at src/trealla.c:1308
#7  0x0000000000404f9b in main (ac=2, av=0x7ffcbbf10c38) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
