### ISSUE TITLE
Segmentation fault when eval `=..` on REPL

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#147]
Eval following `=..` expression on REPL will cause segmentation fault.

Output:

```
% tpl
Trealla v0.1alpha, Jun  9 2017
?- T =.. L.
 L: L
Segmentation fault (core dumped)
```

Backtrace:

```
Core was generated by `tpl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043e4bb in sprint2_compound (depth=1, dstbuf=0x7ffeca1cd8e0, bufsize=0x7ffeca1cd8e8, _dst=0x7ffeca1cd7f8,
    pl=0x17fc010, q=0x1820630, n=0x1821210, listing=1) at src/print.c:205
205             if (is_atom(nf)) {
(gdb) bt
#0  0x000000000043e4bb in sprint2_compound (depth=1, dstbuf=0x7ffeca1cd8e0, bufsize=0x7ffeca1cd8e8, _dst=0x7ffeca1cd7f8,
    pl=0x17fc010, q=0x1820630, n=0x1821210, listing=1) at src/print.c:205
#1  0x000000000043fbef in sprint2_term (depth=1, dstbuf=0x7ffeca1cd8e0, bufsize=0x7ffeca1cd8e8, _dst=0x7ffeca1cd8d8,
    pl=0x17fc010, q=0x1820630, _n=0x1821010, listing=1) at src/print.c:381
#2  0x0000000000440f08 in term_sprint (dstbuf_=0x7ffeca1cd910 "L", bufsize=65536, pl=0x17fc010, q=0x1820630, n=0x1821010,
    listing=1) at src/print.c:545
#3  0x0000000000408b1e in query_dump (self=0x1820630) at src/trealla.c:1092
#4  0x0000000000405432 in main (ac=1, av=0x7ffeca1de568) at tpl.c:443
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
