### ISSUE TITLE
Parsing error for negation

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#153]
Following code will cause segmentation fault:

```
:- initialization(main).

main :- write(-1-2), nl, halt.
```

Backtrace:

```
Core was generated by `tpl -l foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f31d6b1ecc0 in _IO_vfprintf_internal (s=0x7f31d6e94620 <_IO_2_1_stdout_>, format=<optimized out>,
    ap=ap@entry=0x7ffee9059388) at vfprintf.c:1632
1632    vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007f31d6b1ecc0 in _IO_vfprintf_internal (s=0x7f31d6e94620 <_IO_2_1_stdout_>, format=<optimized out>,
    ap=ap@entry=0x7ffee9059388) at vfprintf.c:1632
#1  0x00007f31d6b25899 in __printf (format=<optimized out>) at printf.c:33
#2  0x0000000000413f4f in lexer_parse (self=0x7ffee905bfe0, term=0x1086460, src=0x1083312 "), nl, halt.", line=0x7ffee90597d0)
    at src/parser.c:2528
#3  0x0000000000413049 in lexer_parse (self=0x7ffee905bfe0, term=0x10823b0, src=0x108330e "-1-2), nl, halt.",
    line=0x7ffee90597d0) at src/parser.c:2343
#4  0x00000000004141ad in lexer_parse (self=0x7ffee905bfe0, term=0x0, src=0x0, line=0x7ffee90597d0) at src/parser.c:2569
#5  0x0000000000414362 in lexer_consult_fp (self=0x7ffee905bfe0, fp=0x10830d0) at src/parser.c:2607
#6  0x00000000004146de in lexer_consult_file (self=0x7ffee905bfe0, orig_filename=0x7ffee905e817 "foo.pro") at src/parser.c:2671
#7  0x0000000000409ea2 in trealla_consult_file (self=0x1074010, filename=0x7ffee905e817 "foo.pro") at src/trealla.c:1306
#8  0x000000000040525a in main (ac=3, av=0x7ffee905ce48) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
