### ISSUE TITLE
Segmentation error for tracing

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#160]
Following code will cause segmentation error when run with `tpl --trace`:

```
:- initialization(main).

foo(_).

main :- foo([1|2]), halt.
```

**Comment by dram** [comment]
Backtrace:

```
Core was generated by `tpl --trace foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x00000000004438bc in sprint2_list (depth=4, dstbuf=0x7ffd4b9111f8, bufsize=0x7ffd4b9111f0, _dst=0x7ffd4b90dec0,
    pl=0x2b4a010, q=0x2b59030, n=0x2b5c690, listing=1) at src/print.c:175
#2  0x0000000000445449 in sprint2_term (depth=3, dstbuf=0x7ffd4b9111f8, bufsize=0x7ffd4b9111f0, _dst=0x7ffd4b90efc8,
    pl=0x2b4a010, q=0x2b59030, _n=0x2b5c690, listing=1) at src/print.c:383
#3  0x0000000000444dd4 in sprint2_compound (depth=2, dstbuf=0x7ffd4b9111f8, bufsize=0x7ffd4b9111f0, _dst=0x7ffd4b9100d0,
    pl=0x2b4a010, q=0x2b59030, n=0x2b5c690, listing=1) at src/print.c:323
#4  0x00000000004454ba in sprint2_term (depth=1, dstbuf=0x7ffd4b9111f8, bufsize=0x7ffd4b9111f0, _dst=0x7ffd4b911200,
    pl=0x2b4a010, q=0x2b59030, _n=0x2b5c640, listing=1) at src/print.c:385
#5  0x000000000044693f in term_sprint2 (dstbuf=0x7ffd4b9111f8, bufsize=0x7ffd4b9111f0, dst=0x7ffd4b911200, pl=0x2b4a010,
    q=0x2b59030, n=0x2b5c640, listing=1) at src/print.c:541
#6  0x0000000000408a22 in trace (q=0x2b59030, fail=0, leave=0) at src/trealla.c:891
#7  0x0000000000441591 in call (q=0x2b59030) at src/jela.c:417
#8  0x00000000004417a0 in run_me (q=0x2b59030) at src/jela.c:472
#9  0x0000000000408b53 in query_run (self=0x2b59030) at src/trealla.c:914
#10 0x000000000040a395 in trealla_run_query (self=0x2b4a010, src=0x2b58560 "main.") at src/trealla.c:1403
#11 0x0000000000409f31 in trealla_consult_file (self=0x2b4a010, filename=0x7ffd4b912809 "foo.pro") at src/trealla.c:1306
#12 0x00000000004052aa in main (ac=3, av=0x7ffd4b912168) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
