### ISSUE TITLE
Bootstrapping ?-Prolog

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#161]
With recent massive fixes, the process of using Trealla to bootstrap ?-Prolog goes well.

Will be busy recently, so I record current status here, anyone interested can pick up and go further.

Clone [?-Prolog](https://bitbucket.org/bunny351/prolog) code, replace `pc` with following code (based on `all.pl` and `swi.pl`), and then run `make`:

```
#!/bin/sh

export COMMAND_ARGUMENTS="$*"

exec tpl -q --consult <<EOF

:- op(400, yfx, '\\\\\\\\').
:- op(1150, fx, determinate).
:- op(1150, fx, mode).

determinate(_).
mode(_).

command_line_arguments(Args) :-
        sys:getenv('COMMAND_ARGUMENTS', ArgumentString),
        sys:split_all(ArgumentString, ' ', Args).

dbreference(_) :- fail.         % sufficient here

enable_trace(_).

current_error_output(S) :- current_output(S).

%% this must produce identical results as hash_name() in pc.h
atom_hash(A, H) :-
        atom_codes(A, AL),
        atom_hash(0, AL, 0, H).
atom_hash(I, AL, H, H) :-
        (I >= 100; AL == []), !.
atom_hash(I, [C|R], H1, H2) :-
        H is (H1 xor ((H1 << 6) + (H1 >> 2) + C)) /\\ 1073741823,
        I2 is I + 1,
        atom_hash(I2, R, H, H2).

skip_shebang :- \\+ peek_char('#').
skip_shebang :- repeat, get0(10).

getenv(Name, Value) :- sys:getenv(Name, Value).

display(X) :- write(X).
display(S, X) :- write(S, X).

name(Atom, List) :- atom_codes(Atom, List).

get0(Code) :- get_code(Code).

memberchk(E, L) :- once(member(E, L)).

put(S, C) :- put_code(S, C).

exists_file(File) :- sys:exists_file(File).

append([], []).
append([List |RestLists], Concatenated) :-
        append(RestLists, RestConcatenated),
        append(List, RestConcatenated, Concatenated).

union([], List, List).
union([X| Rest], List, Unioned) :-
        (
                memberchk(X, List)
        ->
                union(Rest, List, Unioned)
        ;
                union(Rest, List, RestUnioned),
                Unioned = [X| RestUnioned]
        ).

:- include('settings.pl').
:- include('lib/rdtok.pl').
:- include('lib/read.pl').
:- include('support.pl').
:- include('state.pl').
:- include('terms.pl').
:- include('index.pl').
:- include('lib/dcg.pl').
:- include('builtin.pl').
:- include('process.pl').
:- include('compile.pl').
:- include('assemble.pl').
:- include('xref.pl').
:- include('dce.pl').
:- include('main.pl').

show_version_and_exit :- display('<none>\\n'), halt.

EOF
```

**Comment by infradig** [comment]
I'll have look. Has been useful to track down bugs, so thanks, much
appreciated.

**Comment by dram** [comment]
Now an infinate loop is encountered when processing included files:

```
...
% including settings.pl
% including settings.pl
% including settings.pl
...
```

I think it is caused by [`process_input/4`](https://bitbucket.org/bunny351/prolog/src/11ecf1b6a865e9a0eac9d5a708e4599855bda1c1/process.pl?at=master&fileviewer=file-view-default#process.pl-44:56) when processing `end_of_file` token.

In SWI-Prolog, `seeing/1` will return a stream object, which remained open. While in Trealla, an atom is returned. If pass result of `seeing/1` again to `see/1`, SWI will continue to read from previous offset, while Trella will return to start of file.

**Comment by infradig** [comment]
Yes, was just looking and wondering about that.

**Comment by infradig** [comment]
That means in 00156.sh seeing can no longer return 'foo.pro' but a stream
reference.

**Comment by dram** [comment]
Now stopped by triggering an assertion error of `malloc`:

```
% make >trace.out
tpl: malloc.c:2866: mremap_chunk: Assertion `((size + offset) & (GLRO (dl_pagesize) - 1)) == 0' failed.
make: *** [pc1.c] Aborted (core dumped)
```

Backtrace:

```
Core was generated by `tpl -q --consult'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f6403eff428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f6403eff428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f6403f0102a in __GI_abort () at abort.c:89
#2  0x00007f6403f472e8 in __malloc_assert (
    assertion=assertion@entry=0x7f640405a280 "((size + offset) & (GLRO (dl_pagesize) - 1)) == 0",
    file=file@entry=0x7f6404056fe5 "malloc.c", line=line@entry=2866,
    function=function@entry=0x7f640405ada0 <__func__.11564> "mremap_chunk") at malloc.c:301
#3  0x00007f6403f475a3 in mremap_chunk (p=p@entry=0x7f6401dc1000, new_size=new_size@entry=33554448) at malloc.c:2866
#4  0x00007f6403f4dbbc in __GI___libc_realloc (oldmem=0x7f6401dc1010, bytes=33554432) at malloc.c:3023
#5  0x0000000000442e93 in grow_environment (q=0x115ba10) at src/jela.c:71
#6  0x0000000000443184 in prepare_frame (q=0x115ba10, frame_size=2) at src/jela.c:122
#7  0x00000000004453ab in match (q=0x115ba10) at src/jela.c:739
#8  0x0000000000444344 in call (q=0x115ba10) at src/jela.c:437
#9  0x00000000004444cd in run_me (q=0x115ba10) at src/jela.c:481
#10 0x0000000000408b53 in query_run (self=0x115ba10) at src/trealla.c:916
#11 0x000000000040a3ac in trealla_run_query (self=0xf3f010, src=0x1150370 "main.") at src/trealla.c:1395
#12 0x0000000000409e61 in trealla_consult_fp (self=0xf3f010, fp=0x7f640428d8e0 <_IO_2_1_stdin_>) at src/trealla.c:1277
#13 0x00000000004052b8 in main (ac=3, av=0x7fff08ead048) at tpl.c:369
(gdb)
```

**Comment by infradig** [comment]
Yes, running out of memory.

**Comment by dram** [comment]
I tested on a VM and a real machine, both memory are quite sufficient.

**Comment by infradig** [comment]
Yes, its probably run-away, or not recovering environment space.

**Comment by dram** [comment]
valgrind detect some memory errors related to `grow_environment` and `realloc`, which may be useful:

```
==7983== Invalid read of size 8
==7983==    at 0x414D03: get_env (bifs.h:339)
==7983==    by 0x414D80: get_arg (bifs.h:349)
==7983==    by 0x415B63: copy_term2 (bifs_iso.c:256)
==7983==    by 0x427766: bif_iso_univ (bifs_iso.c:3438)
==7983==    by 0x44432E: call (jela.c:441)
==7983==    by 0x444505: run_me (jela.c:493)
==7983==    by 0x408B92: query_run (trealla.c:916)
==7983==    by 0x40A3EB: trealla_run_query (trealla.c:1395)
==7983==    by 0x409EA0: trealla_consult_fp (trealla.c:1277)
==7983==    by 0x4052F7: main (tpl.c:369)
==7983==  Address 0x91da050 is 16 bytes after a block of size 2,097,152 alloc'd
==7983==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==7983==    by 0x442EBF: grow_environment (jela.c:79)
==7983==    by 0x4431BC: prepare_frame (jela.c:134)
==7983==    by 0x4453E3: match (jela.c:751)
==7983==    by 0x44437C: call (jela.c:449)
==7983==    by 0x444505: run_me (jela.c:493)
==7983==    by 0x408B92: query_run (trealla.c:916)
==7983==    by 0x40A3EB: trealla_run_query (trealla.c:1395)
==7983==    by 0x409EA0: trealla_consult_fp (trealla.c:1277)
==7983==    by 0x4052F7: main (tpl.c:369)
==7983==
==7983== Invalid read of size 4
==7983==    at 0x414D0F: get_env (bifs.h:339)
==7983==    by 0x414D80: get_arg (bifs.h:349)
==7983==    by 0x415B63: copy_term2 (bifs_iso.c:256)
==7983==    by 0x427766: bif_iso_univ (bifs_iso.c:3438)
==7983==    by 0x44432E: call (jela.c:441)
==7983==    by 0x444505: run_me (jela.c:493)
==7983==    by 0x408B92: query_run (trealla.c:916)
==7983==    by 0x40A3EB: trealla_run_query (trealla.c:1395)
==7983==    by 0x409EA0: trealla_consult_fp (trealla.c:1277)
==7983==    by 0x4052F7: main (tpl.c:369)
==7983==  Address 0x91da058 is 24 bytes after a block of size 2,097,152 in arena "client"
==7983==
==7983== Invalid read of size 8
==7983==    at 0x415913: copy_term2 (bifs_iso.c:216)
==7983==    by 0x415B80: copy_term2 (bifs_iso.c:257)
==7983==    by 0x427766: bif_iso_univ (bifs_iso.c:3438)
==7983==    by 0x44432E: call (jela.c:441)
==7983==    by 0x444505: run_me (jela.c:493)
==7983==    by 0x408B92: query_run (trealla.c:916)
==7983==    by 0x40A3EB: trealla_run_query (trealla.c:1395)
==7983==    by 0x409EA0: trealla_consult_fp (trealla.c:1277)
==7983==    by 0x4052F7: main (tpl.c:369)
==7983==  Address 0x1000000c8434 is not stack'd, malloc'd or (recently) free'd
==7983==
==7983==
==7983== Process terminating with default action of signal 11 (SIGSEGV)
==7983==  Access not within mapped region at address 0x1000000C8434
==7983==    at 0x415913: copy_term2 (bifs_iso.c:216)
==7983==    by 0x415B80: copy_term2 (bifs_iso.c:257)
==7983==    by 0x427766: bif_iso_univ (bifs_iso.c:3438)
==7983==    by 0x44432E: call (jela.c:441)
==7983==    by 0x444505: run_me (jela.c:493)
==7983==    by 0x408B92: query_run (trealla.c:916)
==7983==    by 0x40A3EB: trealla_run_query (trealla.c:1395)
==7983==    by 0x409EA0: trealla_consult_fp (trealla.c:1277)
==7983==    by 0x4052F7: main (tpl.c:369)
==7983==  If you believe this happened as a result of a stack
==7983==  overflow in your program's main thread (unlikely but
==7983==  possible), you can try to increase the size of the
==7983==  main thread stack using the --main-stacksize= flag.
==7983==  The main thread stack size used in this run was 8388608.
==7983==
```

**Comment by dram** [comment]
Seems that bootstrapping ?-Prolog still has a long way to go, and now it becomes harder to spot the problems.

I wll go another way first, using ?-Prolog bulitin test cases (run with `./run-checks`), hope that will help.

**Comment by dram** [comment]
With the fix of issue #178, now `./pc tests/0001-true.pl` failed with a segmentation fault:

```
Core was generated by `tpl -q --consult'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000414d66 in get_env (q=0x2640e60, point=4294967295) at src/bifs.h:339
339             return e->term ? e : e - e->binding;
(gdb) bt
#0  0x0000000000414d66 in get_env (q=0x2640e60, point=4294967295) at src/bifs.h:339
#1  0x0000000000414de4 in get_arg (q=0x2640e60, term=0x2640190, frame=4294967295) at src/bifs.h:349
#2  0x0000000000415b5d in copy_term2 (q=0x2640e60, from=0x2640190, clone=1, depth=1) at src/bifs_iso.c:255
#3  0x0000000000415b7a in copy_term2 (q=0x2640e60, from=0x26400f0, clone=1, depth=0) at src/bifs_iso.c:256
#4  0x00000000004294f6 in bif_iso_findall (q=0x2640e60) at src/bifs_iso.c:3787
#5  0x0000000000445791 in call (q=0x2640e60) at src/jela.c:441
#6  0x0000000000445968 in run_me (q=0x2640e60) at src/jela.c:493
#7  0x0000000000408b87 in query_run (self=0x2640e60) at src/trealla.c:912
#8  0x000000000040a3cd in trealla_run_query (self=0x2426010, src=0x2638e30 "main.") at src/trealla.c:1387
#9  0x0000000000409e82 in trealla_consult_fp (self=0x2426010, fp=0x7f1925cd98e0 <_IO_2_1_stdin_>) at src/trealla.c:1271
#10 0x0000000000405310 in main (ac=3, av=0x7ffe5554eb78) at tpl.c:369
(gdb)
```

**Comment by infradig** [comment]
I did notice this:

andrew@andrew:~/prolog$ make
./pc -n pc.pl -o pc1.c
% including settings.pl
% including support.pl
ERROR: invalid arithmetic expression:
iota('_var_'(1),[var('_var_'(1),'N'),',',var('_var_'(2),'M'),',','[',var('_var_'(1),'N'),'|',var('_var_'(3),'R'),']',')',atom(:-),var('_var_'(0),'N2'),atom(is),var('_var_'(1),'N'),atom(+),integer(1),',',atom(iota),'(',var('_var_'(0),'N2'),',',var('_var_'(2),'M'),',',var('_var_'(3),'R'),')'],[[],',',var('_var_'(2),'M'),',','[',var('_var_'(1),'N'),'|',var('_var_'(3),'R'),']',')',atom(:-),var('_var_'(0),'N2'),atom(is),var('_var_'(1),'N'),atom(+),integer(1),',',atom(iota),'(',var('_var_'(0),'N2'),',',var('_var_'(2),'M'),',',var('_var_'(3),'R'),')'])

GNUmakefile:48: recipe for target 'pc1.c' failed
make: *** [pc1.c] Error 1
andrew@andrew:~/prolog$

**Comment by dram** [comment]
Add another test for issue #178, which may be related to segmentation fault error I mentioned.

**Comment by dram** [comment]
With recent fix of #178, now `pc` can compile `tests/0001-true.pl` file to a `.c` file now!

Although comparing to output of SWI-Prolog, there are 9 lines missing, so the result is not correct. But anyway, quite exciting.

**Comment by infradig** [comment]
Yes, this is progress. Many rivers to cross, as the saying goes.

**Comment by dram** [comment]
The `grow_environment` related memory error mentioned previously still exists, which can be detected by just modify `pc` to use `valgrind tpl` instead of `tpl`, and then run `./pc tests/0001-true.pl`.

Have some time to look into this problem, I found that it may caused by `copy_term2` and `get_arg`, according to the backtrace:

```
==2073== Invalid read of size 8
==2073==    at 0x414D66: get_env (bifs.h:339)
==2073==    by 0x414DEF: get_arg (bifs.h:352)
==2073==    by 0x415B68: copy_term2 (bifs_iso.c:255)
==2073==    by 0x427E43: bif_iso_univ (bifs_iso.c:3515)
==2073==    by 0x4457A8: call (jela.c:441)
==2073==    by 0x44597F: run_me (jela.c:493)
==2073==    by 0x408B86: query_run (trealla.c:912)
==2073==    by 0x40A3CC: trealla_run_query (trealla.c:1387)
==2073==    by 0x409E81: trealla_consult_fp (trealla.c:1271)
==2073==    by 0x40530F: main (tpl.c:369)
==2073==  Address 0x6acdef0 is 0 bytes after a block of size 32,768 alloc'd
==2073==    at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2073==    by 0x44434D: grow_environment (jela.c:79)
==2073==    by 0x444636: prepare_frame (jela.c:134)
==2073==    by 0x4468DF: match (jela.c:760)
==2073==    by 0x4457F6: call (jela.c:449)
==2073==    by 0x44597F: run_me (jela.c:493)
==2073==    by 0x408B86: query_run (trealla.c:912)
==2073==    by 0x40A3CC: trealla_run_query (trealla.c:1387)
==2073==    by 0x409E81: trealla_consult_fp (trealla.c:1271)
==2073==    by 0x40530F: main (tpl.c:369)
```

After I apply following change, the problem disappeared, not sure if this change is appropriate, as there are several if-else branches in `get_arg`, and I can not fully grasp the purpose of the function.

```
--- a/src/bifs.h
+++ b/src/bifs.h
@@ -341,6 +341,8 @@ inline static env *get_env(tpl_query *q, unsigned point)

 inline static node *get_arg(tpl_query *q, node *term, unsigned frame)
 {
+       const env *e;
+
        if (!is_var(term)) {
                q->latest_context = frame;
                return term;
@@ -349,9 +351,12 @@ inline static node *get_arg(tpl_query *q, node *term, unsigned frame)
        if ((signed)frame == -1)
                return term;

-       const env *e = get_env(q, frame + term->slot);
+       if (frame + term->slot >= q->envs_possible)
+               e = NULL;
+       else
+               e = get_env(q, frame + term->slot);

-       if (e->term != NULL) {
+       if (e != NULL && e->term != NULL) {
                q->latest_context = e->context;
                return e->term;
        }
```

**Comment by dram** [comment]
After #191 fix, `pc` will go into an infinite loop when compiling `tests/0001-true.pl`, caused by incorrect `=..` unification, I can not extract a simple test case, so just paste a snippet of trace output:

```
...
Call: (true,(true,main))=..L
Exit: (true,(true,main))=..[',',IGOAL,(PGOAL,GOAL)]
...
```
