### ISSUE TITLE
Segmentation fault for functor/3

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#166]
Following code will cause segmentation fault for `tpl`, which is related to issue #161 

```
:- initialization(main).

main :- functor(a,b,1).
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
29      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
#1  0x00000000004251b9 in bif_iso_functor (q=0x18bc700) at src/bifs_iso.c:3488
#2  0x00000000004407fd in call (q=0x18bc700) at src/jela.c:429
#3  0x00000000004409d3 in run_me (q=0x18bc700) at src/jela.c:481
#4  0x00000000004082c6 in query_run (self=0x18bc700) at src/trealla.c:916
#5  0x0000000000409987 in trealla_run_query (self=0x18ab010, src=0x18be9f0 "main.") at src/trealla.c:1395
#6  0x00000000004095b6 in trealla_consult_file (self=0x18ab010, filename=0x7ffe06043818 "foo.pro") at src/trealla.c:1296
#7  0x0000000000404f9b in main (ac=2, av=0x7ffe06041e58) at tpl.c:363
(gdb)
```

**Comment by infradig** [comment]
Mine doesn't crash but I can see the problem.

**Comment by dram** [comment]
Fix confirmed, thanks.
