### ISSUE TITLE
Segmentation fault for export/1 directive

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#173]
Following code (superfluous `,` inside list of `export/1`) will cause Segmentation fault for `export/1` directive:

```
:- module(foo).

:- export([foo/0,]).

foo.
```

Backtrace:

```
Core was generated by `tpl -q --ns foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000040c941 in dir_export (l=0x7ffcc4a47630, n=0x16005e0) at src/parser.c:709
709                     while (is_list(term1)) {
(gdb) bt
#0  0x000000000040c941 in dir_export (l=0x7ffcc4a47630, n=0x16005e0) at src/parser.c:709
#1  0x000000000040d6e8 in directive (l=0x7ffcc4a47630, n=0x15fc8e0) at src/parser.c:1005
#2  0x0000000000410a32 in lexer_finalize (self=0x7ffcc4a47630) at src/parser.c:2104
#3  0x0000000000412ec4 in lexer_parse (self=0x7ffcc4a47630, term=0x1603250, src=0x1608f04 "", line=0x7ffcc4a44e48)
    at src/parser.c:2625
#4  0x0000000000412fb2 in lexer_parse (self=0x7ffcc4a47630, term=0x0, src=0x0, line=0x7ffcc4a44e48) at src/parser.c:2640
#5  0x0000000000413144 in lexer_consult_fp (self=0x7ffcc4a47630, fp=0x15f88c0) at src/parser.c:2678
#6  0x0000000000413466 in lexer_consult_file (self=0x7ffcc4a47630, orig_filename=0x7ffcc4a4883a "foo.pro") at src/parser.c:2740
#7  0x000000000040960a in trealla_consult_file (self=0x15f4010, filename=0x7ffcc4a4883a "foo.pro") at src/trealla.c:1292
#8  0x0000000000404fdb in main (ac=4, av=0x7ffcc4a483f8) at tpl.c:363
(gdb)
```

**Comment by infradig** [comment]
This is the same as #168, so i'll close this for now.

**Comment by dram** [comment]
Fix confirmed, thanks.
