### ISSUE TITLE
Memory error when `see/1` a non-exists file

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#175]
Following code will cause memory error:

```
:- initialization(main).

main :- see('foo/bar.file'), halt.
```

Output:

```
% tpl foo.pro
ERROR: ERROR ABORT_NOTEXISTFILE
Segmentation fault (core dumped)
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f31e86294d8 in _int_free (av=0x7f31e8955620 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3996
3996    malloc.c: No such file or directory.
(gdb) bt
#0  0x00007f31e86294d8 in _int_free (av=0x7f31e8955620 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3996
#1  0x00000000004471c1 in sl_done (d=0x28a2a20, deleter=0x0) at src/skiplist.c:307
#2  0x00000000004108ea in lexer_done (self=0x28a2960) at src/parser.c:2067
#3  0x0000000000410752 in lexer_destroy (self=0x28a2960) at src/parser.c:2038
#4  0x00000000004094de in query_destroy (self=0x28b5570) at src/trealla.c:1252
#5  0x0000000000409a58 in trealla_run_query (self=0x289e010, src=0x28b3fd0 "main.") at src/trealla.c:1390
#6  0x000000000040963b in trealla_consult_file (self=0x289e010, filename=0x7fff58eaa811 "foo.pro") at src/trealla.c:1286
#7  0x0000000000404ff3 in main (ac=2, av=0x7fff58ea8ec8) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Thanks.
