### ISSUE TITLE
Segmentation fault when using `=..` in REPL

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#192]
Following shell script will cause segmentation fault:

```
tpl <<EOF
(foo,(bar,baz)) =.. L.
EOF
```

Backtrace:

```
Core was generated by `tpl'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e0a08738a3 in sprint2_compound (depth=5, dstbuf=0x7ffcea854198, bufsize=0x7ffcea8541a0, _dst=0x7ffcea853f48,
    pl=0x55e0a1a0e010, q=0x0, n=0x55e0a1a228b0, listing=1) at src/print.c:232
232                     if ((strcmp(functor, ":-") && strcmp(functor, "-->") && strcmp(functor, "is")) && (q->print_depth > 2)) {
(gdb) bt
#0  0x000055e0a08738a3 in sprint2_compound (depth=5, dstbuf=0x7ffcea854198, bufsize=0x7ffcea8541a0, _dst=0x7ffcea853f48,
    pl=0x55e0a1a0e010, q=0x0, n=0x55e0a1a228b0, listing=1) at src/print.c:232
#1  0x000055e0a0874d08 in sprint2_term (depth=5, dstbuf=0x7ffcea854198, bufsize=0x7ffcea8541a0, _dst=0x7ffcea854020,
    pl=0x55e0a1a0e010, q=0x0, _n=0x55e0a1a228b0, listing=1) at src/print.c:403
#2  0x000055e0a0873223 in sprint2_list (depth=4, dstbuf=0x7ffcea854198, bufsize=0x7ffcea8541a0, _dst=0x7ffcea8540b8,
    pl=0x55e0a1a0e010, q=0x0, n=0x55e0a1a22810, listing=1) at src/print.c:168
#3  0x000055e0a0874c9d in sprint2_term (depth=1, dstbuf=0x7ffcea854198, bufsize=0x7ffcea8541a0, _dst=0x7ffcea854190,
    pl=0x55e0a1a0e010, q=0x0, _n=0x55e0a1a264f0, listing=1) at src/print.c:401
#4  0x000055e0a0876287 in term_sprint (dstbuf=0x7ffcea8541d0 "", bufsize=65536, pl=0x55e0a1a0e010, q=0x0, n=0x55e0a1a264f0,
    listing=1) at src/print.c:570
#5  0x000055e0a0833f1c in query_dump (q=0x55e0a1a256a0) at src/trealla.c:1075
#6  0x000055e0a08306f8 in main (ac=1, av=0x7ffcea864e38) at tpl.c:443
(gdb)
```

**Comment by infradig** [comment]
A simple

  ?- (foo,(bar,baz)) = L.

will do it.

**Comment by dram** [comment]
Fix confirmed, thanks.

**Comment by infradig** [comment]
Oops, 1e56798 had nothing to do with #192.
