### ISSUE TITLE
Segmentation fault for 

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#202]
Following code will cause Segmentation fault for `=..`:

```
:- initialization(main).

main :-
        L = [a],
        T =.. [foo| L],
        write(T), nl,
        halt.
```

Backtrace:

```
Core was generated by `tpl prolog/foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
b#0  0x000055857ecceb10 in term_next (n=0x6f6f66) at src/bifs.h:487
487     inline static node *term_next(node *n) { return NLIST_NEXT(n); }
(gdb) bt
#0  0x000055857ecceb10 in term_next (n=0x6f6f66) at src/bifs.h:487
#1  0x000055857eccec8a in term_firstarg (s=0x55857fb07560) at src/bifs.h:499
#2  0x000055857ecd0b3c in xref_clause (l=0x55857fafaeb0, term=0x55857fb07560) at src/trealla.c:684
#3  0x000055857ecf074d in bif_iso_univ (q=0x55857fb06830) at src/bifs_iso.c:3579
#4  0x000055857ed1066e in call (q=0x55857fb06830) at src/jela.c:441
#5  0x000055857ed10845 in run_me (q=0x55857fb06830) at src/jela.c:493
#6  0x000055857ecd1723 in query_run (q=0x55857fb06830) at src/trealla.c:909
#7  0x000055857ecd2d16 in trealla_run_query (pl=0x55857faf3010, src=0x55857fb02e60 "main.") at src/trealla.c:1384
#8  0x000055857ecd2943 in trealla_consult_file (pl=0x55857faf3010, filename=0x7fffc320b7ee "prolog/foo.pro")
    at src/trealla.c:1287
#9  0x000055857ecce27c in main (ac=2, av=0x7fffc320a9c8) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
