### ISSUE TITLE
Segmentation fault for record

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#206]
Following code will cause segmentation fault:

```
:- initialization(main).

main :-
        recordz(foo, foo(1)),
        recorded(foo, _, R1),
        erase(R1),
        recorded(foo, A2, _),
        write(A2), nl,
        halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055fc4df5b042 in list_remove (l=0x55fc4f98d110, entry=0x55fc4f98f6d0) at src/list.c:101
101                     entry->next->prev = entry->prev;
(gdb) bt
#0  0x000055fc4df5b042 in list_remove (l=0x55fc4f98d110, entry=0x55fc4f98f6d0) at src/list.c:101
#1  0x000055fc4df382c6 in bif_clause (q=0x55fc4f98c150, wait=0) at src/bifs_iso.c:3139
#2  0x000055fc4df38586 in bif_iso_clause (q=0x55fc4f98c150) at src/bifs_iso.c:3185
#3  0x000055fc4df598ad in call (q=0x55fc4f98c150) at src/jela.c:461
#4  0x000055fc4df59a84 in run_me (q=0x55fc4f98c150) at src/jela.c:513
#5  0x000055fc4df1b864 in query_run (q=0x55fc4f98c150) at src/trealla.c:913
#6  0x000055fc4df1ce55 in trealla_run_query (pl=0x55fc4f96b010, src=0x55fc4f97bc10 "main.") at src/trealla.c:1388
#7  0x000055fc4df1ca82 in trealla_consult_file (pl=0x55fc4f96b010, filename=0x7ffea1f7f4fb "foo.pro") at src/trealla.c:1291
#8  0x000055fc4df1832c in main (ac=2, av=0x7ffea1f7f068) at tpl.c:363
(gdb) 
```

**Comment by dram** [comment]
Fix confirmed, thanks.
