### ISSUE TITLE
Segmentation fault for `=..`

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#216]
Following code will cause segmentation fault for `=..`:

```
:- initialization(main).

main :- A =.. [foo], write(A), nl, halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558d1cf42bf0 in term_next (n=0x6f6f66) at src/bifs.h:486
486     inline static node *term_next(node *n) { return NLIST_NEXT(n); }
(gdb) bt
#0  0x0000558d1cf42bf0 in term_next (n=0x6f6f66) at src/bifs.h:486
#1  0x0000558d1cf42d6a in term_firstarg (s=0x558d1ef3fe90) at src/bifs.h:498
#2  0x0000558d1cf44d33 in xref_clause (l=0x558d1ef2dc80, term=0x558d1ef3fe90) at src/trealla.c:707
#3  0x0000558d1cf64592 in bif_iso_univ (q=0x558d1ef3e090) at src/bifs_iso.c:3565
#4  0x0000558d1cf847b0 in call (q=0x558d1ef3e090) at src/jela.c:463
#5  0x0000558d1cf84987 in run_me (q=0x558d1ef3e090) at src/jela.c:515
#6  0x0000558d1cf4591a in query_run (q=0x558d1ef3e090) at src/trealla.c:932
#7  0x0000558d1cf46f7b in trealla_run_query (pl=0x558d1ef1d010, src=0x558d1ef2a780 "main.") at src/trealla.c:1423
#8  0x0000558d1cf46ba8 in trealla_consult_file (pl=0x558d1ef1d010, filename=0x7fff924c27ed "foo.pro") at src/trealla.c:1326
#9  0x0000558d1cf4235c in main (ac=2, av=0x7fff924c22e8) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
