### ISSUE TITLE
Segmentation fault when parsing DCG clause

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#224]
Trealla failed to parse following DCG clause:

```
:- initialization(main).

as --> [a], [b].

main :-
        phrase(as, [X, _]), write(X), nl, halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055da5044b7d9 in list_remove (l=0x55da512b8d60, entry=0x55da512a44c0) at src/list.c:101
101                     entry->next->prev = entry->prev;
(gdb) bt
#0  0x000055da5044b7d9 in list_remove (l=0x55da512b8d60, entry=0x55da512a44c0) at src/list.c:101
#1  0x000055da5040acca in term_remove (s=0x55da512b8d50, n=0x55da512a44c0) at src/bifs.h:488
#2  0x000055da5040fabf in dcg_clause (l=0x7ffd93ab2b50, term=0x55da512b8d50) at src/parser.c:1469
#3  0x000055da50411db4 in lexer_finalize (l=0x7ffd93ab2b50) at src/parser.c:2181
#4  0x000055da50414203 in lexer_parse (l=0x7ffd93ab2b50, term=0x55da512b4ac0, src=0x55da512b5cf0 "", line=0x7ffd93ab0368)
    at src/parser.c:2658
#5  0x000055da504142f1 in lexer_parse (l=0x7ffd93ab2b50, term=0x0, src=0x0, line=0x7ffd93ab0368) at src/parser.c:2673
#6  0x000055da50414485 in lexer_consult_fp (l=0x7ffd93ab2b50, fp=0x55da512a40b0) at src/parser.c:2711
#7  0x000055da504147d5 in lexer_consult_file (l=0x7ffd93ab2b50, orig_filename=0x7ffd93ab57d4 "foo.pro") at src/parser.c:2772
#8  0x000055da50409c36 in trealla_consult_file (pl=0x55da51293010, filename=0x7ffd93ab57d4 "foo.pro") at src/trealla.c:1325
#9  0x000055da5040541c in main (ac=2, av=0x7ffd93ab3908) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
