### ISSUE TITLE
Segmentation fault for superfluous `,` inside list

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#248]
Following code will cause segmentation fault:

```
:- initialization(main).

main :-
        write([a, b, ]), nl, halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562c0d601c6e in subst (q=0x562c0f2d36b0, term=0x0, frame=1) at src/bifs.h:430
430             if (!is_var(term)) {
(gdb) bt
#0  0x0000562c0d601c6e in subst (q=0x562c0f2d36b0, term=0x0, frame=1) at src/bifs.h:430
#1  0x0000562c0d602484 in sprint2_list (depth=1, dstbuf=0x7fffb4c7b7c8, bufsize=0x7fffb4c7b7c0, _dst=0x7fffb4c7b6a8,
    pl=0x562c0f2ab010, q=0x562c0f2d36b0, n=0x562c0f2d6720, listing=0) at src/print.c:172
#2  0x0000562c0d603c78 in sprint2_term (depth=0, dstbuf=0x7fffb4c7b7c8, bufsize=0x7fffb4c7b7c0, _dst=0x7fffb4c7b7b8,
    pl=0x562c0f2ab010, q=0x562c0f2d36b0, _n=0x562c0f2c2dc0, listing=0) at src/print.c:388
#3  0x0000562c0d6051ae in term_sprint2 (dstbuf=0x7fffb4c7b7c8, bufsize=0x7fffb4c7b7c0, dst=0x7fffb4c7b7b8, pl=0x562c0f2ab010,
    q=0x562c0f2d36b0, n=0x562c0f2c2dc0, listing=0) at src/print.c:553
#4  0x0000562c0d5e03c8 in bif_iso_write (q=0x562c0f2d36b0) at src/bifs_iso.c:1447
#5  0x0000562c0d5ffb95 in call (q=0x562c0f2d36b0) at src/jela.c:463
#6  0x0000562c0d5ffd85 in run_me (q=0x562c0f2d36b0) at src/jela.c:515
#7  0x0000562c0d5cbeca in query_run (q=0x562c0f2d36b0) at src/trealla.c:933
#8  0x0000562c0d5cd593 in trealla_run_query (pl=0x562c0f2ab010, src=0x562c0f2d2c40 "main.") at src/trealla.c:1427
#9  0x0000562c0d5cd1d9 in trealla_consult_file (pl=0x562c0f2ab010, filename=0x7fffb4c7d7db "foo.pro") at src/trealla.c:1331
#10 0x0000562c0d5c88fc in main (ac=2, av=0x7fffb4c7c688) at tpl.c:363
(gdb) 
```

**Comment by dram** [comment]
Fix confirmed, thanks.
