### ISSUE TITLE
Segmentation error for read/2

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#250]
Following code will cause segmentation error:

```
:- initialization(main).

main :-
        open('data.pro', read, Stream),
        read(Stream, Term),
        write(Term), nl,
        halt.
```

data.pro:

```
foo([
]).
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055fe0f644cf2 in subst (q=0x55fe112ef6f0, term=0x0, frame=1) at src/bifs.h:430
430             if (!is_var(term)) {
(gdb) bt
#0  0x000055fe0f644cf2 in subst (q=0x55fe112ef6f0, term=0x0, frame=1) at src/bifs.h:430
#1  0x000055fe0f645508 in sprint2_list (depth=3, dstbuf=0x7fff12152ad8, bufsize=0x7fff12152ad0, _dst=0x7fff121517c8,
    pl=0x55fe112c7010, q=0x55fe112ef6f0, n=0x55fe112f2560, listing=0) at src/print.c:172
#2  0x000055fe0f646cfc in sprint2_term (depth=2, dstbuf=0x7fff12152ad8, bufsize=0x7fff12152ad0, _dst=0x7fff121528b0,
    pl=0x55fe112c7010, q=0x55fe112ef6f0, _n=0x55fe112f2560, listing=0) at src/print.c:388
#3  0x000055fe0f646771 in sprint2_compound (depth=1, dstbuf=0x7fff12152ad8, bufsize=0x7fff12152ad0, _dst=0x7fff121529b8,
    pl=0x55fe112c7010, q=0x55fe112ef6f0, n=0x55fe112f2560, listing=0) at src/print.c:330
#4  0x000055fe0f646d64 in sprint2_term (depth=0, dstbuf=0x7fff12152ad8, bufsize=0x7fff12152ad0, _dst=0x7fff12152ac8,
    pl=0x55fe112c7010, q=0x55fe112ef6f0, _n=0x55fe112f2510, listing=0) at src/print.c:390
#5  0x000055fe0f648232 in term_sprint2 (dstbuf=0x7fff12152ad8, bufsize=0x7fff12152ad0, dst=0x7fff12152ac8, pl=0x55fe112c7010,
    q=0x55fe112ef6f0, n=0x55fe112f2510, listing=0) at src/print.c:553
#6  0x000055fe0f62344f in bif_iso_write (q=0x55fe112ef6f0) at src/bifs_iso.c:1447
#7  0x000055fe0f642c19 in call (q=0x55fe112ef6f0) at src/jela.c:463
#8  0x000055fe0f642e09 in run_me (q=0x55fe112ef6f0) at src/jela.c:515
#9  0x000055fe0f60eeca in query_run (q=0x55fe112ef6f0) at src/trealla.c:933
#10 0x000055fe0f610596 in trealla_run_query (pl=0x55fe112c7010, src=0x55fe112e89d0 "main.") at src/trealla.c:1427
#11 0x000055fe0f6101d9 in trealla_consult_file (pl=0x55fe112c7010, filename=0x7fff121557cd "foo.pro") at src/trealla.c:1331
#12 0x000055fe0f60b8fc in main (ac=2, av=0x7fff12153998) at tpl.c:363
(gdb)
```

**Comment by infradig** [comment]
This is a generic parsing problem:


main :-
writeln( [
]),
halt.

will give the same effect. It comes from not handling the split [].

**Comment by dram** [comment]
Fix confirmed, thanks.
