### ISSUE TITLE
Segmentation fault (proceed at jela.c)

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#252]
Following code will cause segmentation fault (proceed at jela.c), sorry for the long test case, I just failed to simplify further.

```
:- initialization(main).

format(Format, Args, Out) :-
    sys:split_all(Format, '~a', Segments),
    format_helper(Segments, Args, Out).

format_helper([Segment], [], Out) :-
    Out = Segment.
format_helper([Segment| SegmentRest], [Arg| ArgRest], Out) :-
    format_helper(SegmentRest, ArgRest, Rest),
    atomic_list_concat([Segment, Arg, Rest], Out).

file_of_terms(File, Terms) :-
        open(File, read, Stream),
        stream_of_terms(Stream, Terms),
        close(Stream).

stream_of_terms(Stream, Terms) :-
        read(Stream, Term),
        (       Term = end_of_file ->
                Terms = []
        ;       stream_of_terms(Stream, Terms0),
                Terms = [Term| Terms0]
        ).

foo(_).

main :-
        Foo = a,
        foo(Foo),

        file_of_terms('data.pro', Foos),

        forall(
                nth1(
                        _,
                        Foos,
                        foo(A, b(B), c(C), d(D), e(E))
                ),
                (
                        forall(
                                nth1(_, E, E1),
                                (
                                        format('~a~a-', [a, b], _),
                                        bar(E1, A, B, C, D, _)
                                )
                        )
                )
        ), halt.

bar(E, A, b1(B1, B2, B3), c1(C1, C2, C3), D, F) :-
        format(
                '~a~a~a~a~a~a~a~a~a-',
                [E, A, B1, B2, B3, C1, C2, C3, D],
                F
        ).
```

`data.pro`:

```
foo(
        a,
        b(b1(1, 2, 3)),
        c(c1(4, 5, 6)),
        d(7),
        e([8])
).
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055b88fef0df0 in proceed (q=0x55b891bf76f0) at src/jela.c:178
178                     q->c.prev_choice = c->prev_choice;
(gdb) bt
#0  0x000055b88fef0df0 in proceed (q=0x55b891bf76f0) at src/jela.c:178
#1  0x000055b88fef0f70 in follow (q=0x55b891bf76f0) at src/jela.c:212
#2  0x000055b88fef1f6e in run_me (q=0x55b891bf76f0) at src/jela.c:533
#3  0x000055b88febdeca in query_run (q=0x55b891bf76f0) at src/trealla.c:933
#4  0x000055b88febf596 in trealla_run_query (pl=0x55b891bcf010, src=0x55b891bf12e0 "main.") at src/trealla.c:1427
#5  0x000055b88febf1d9 in trealla_consult_file (pl=0x55b891bcf010, filename=0x7fffc7fd47fc "foo.pro") at src/trealla.c:1331
#6  0x000055b88feba8fc in main (ac=2, av=0x7fffc7fd37f8) at tpl.c:363
(gdb)
```

**Comment by dram** [comment]
Fix confirmed, thanks.
