### ISSUE TITLE
Negation call segmentation fault

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#257]
Following code will cause segmentation fault (spotted by ?-Prolog tests/0046-arithmetic.pl):

```
:- initialization(main).

main :- -(3) = -3, write(ok), nl, halt.
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:137
137     ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:137
#1  0x00007fc14749bd78 in _IO_vfprintf_internal (s=s@entry=0x7fff3b7c43b0, format=<optimized out>,
    format@entry=0x5624cc0245d2 "%s", ap=ap@entry=0x7fff3b7c4518) at vfprintf.c:1637
#2  0x00007fc1474c2e59 in _IO_vsnprintf (string=0x7fff3b7c4610 "", maxlen=<optimized out>, format=0x5624cc0245d2 "%s",
    args=args@entry=0x7fff3b7c4518) at vsnprintf.c:114
#3  0x00007fc1474a2292 in __snprintf (s=<optimized out>, maxlen=<optimized out>, format=<optimized out>) at snprintf.c:33
#4  0x00005624cbfa5373 in get_bifarity (l=0x7fff3b7c91a0,
    functor=0xfffffffffffffffd <error: Cannot access memory at address 0xfffffffffffffffd>, arity=0) at src/bifs_iso.c:360
#5  0x00005624cbf9e8f2 in attach_ops (l=0x7fff3b7c91a0, term=0x5624ccc37d40, depth=1) at src/parser.c:1326
#6  0x00005624cbf9dfbd in attach_ops (l=0x7fff3b7c91a0, term=0x5624ccc475d0, depth=0) at src/parser.c:1184
#7  0x00005624cbfa1876 in lexer_finalize (l=0x7fff3b7c91a0) at src/parser.c:2274
#8  0x00005624cbfa3b2b in lexer_parse (l=0x7fff3b7c91a0, term=0x5624ccc475d0, src=0x5624ccc487e7 "", line=0x7fff3b7c69b8)
    at src/parser.c:2789
#9  0x00005624cbfa3c2a in lexer_parse (l=0x7fff3b7c91a0, term=0x0, src=0x0, line=0x7fff3b7c69b8) at src/parser.c:2805
#10 0x00005624cbf9ea0e in lexer_consult_fp (l=0x7fff3b7c91a0, fp=0x5624ccc37ac0) at src/parser.c:1352
#11 0x00005624cbf9ed5e in lexer_consult_file (l=0x7fff3b7c91a0, orig_filename=0x7fff3b7ca7f3 "foo.pro") at src/parser.c:1413
#12 0x00005624cbf99188 in trealla_consult_file (pl=0x5624ccc20010, filename=0x7fff3b7ca7f3 "foo.pro") at src/trealla.c:1327
#13 0x00005624cbf948cc in main (ac=2, av=0x7fff3b7c9f68) at tpl.c:363
(gdb)
```

**Comment by infradig** [comment]
Ok, fixed. NOTE: this test is actually wrong, verified with swipl & yap. I
have updated it in the repo.

**Comment by dram** [comment]
Nice! Closing it.
