### ISSUE TITLE
Segmentation fault when using get_char/1, number_chars/2 and a recursive call

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#9]
Following is code which can reproduce the problem, I failed to simplify this test case any further, so it is a bit long:

```
:- initialization(main).

sum(0, X) :- X is 0.
sum(N, X) :- N1 is N - 1, sum(N1, X1), X is X1 + N.

main :-
    get_char(Char),
    number_chars(N, [Char]),
    sum(N, Sum).
```

Trace output:

```
% ./tpl --trace ../foo.pl 
Trealla v0.1alpha, 64-bits (int=128-bits), Nov 22 2016
Call: ?- main
Exit: ?-
Call: main
Exit: main
Call: get_char(Char)
1
Exit: get_char('1')
Call: number_chars(N,['1'])
Exit: number_chars(1,['1'])
Call: sum(1,Sum)
Segmentation fault (core dumped)
```

Core dump backtrace:

```
(gdb) bt
#0  0x000000000042c15e in get_arg (q=0x7362ef0, term=0x7341e80, frame=0)
    at src/bifs.h:141
#1  0x000000000042d85b in sprint2_compound (dstbuf=0x7ffd46a2eb68, 
    bufsize=0x7ffd46a2eb70, _dst=0x7ffd46a2ead8, pl=0x7227030, q=0x7362ef0, 
    n=0x7341e80, listing=1) at src/print.c:292
#2  0x000000000042dd32 in sprint2_term (dstbuf=0x7ffd46a2eb68, 
    bufsize=0x7ffd46a2eb70, _dst=0x7ffd46a2eb60, pl=0x7227030, q=0x7362ef0, 
    _n=0x7341dc0, listing=1) at src/print.c:338
#3  0x000000000040bfc8 in trace (q=0x7362ef0, fail=0, leave=1)
    at src/trealla.c:2444
#4  0x000000000040c1a9 in query_run (self=0x7362ef0) at src/trealla.c:2487
#5  0x000000000040dafe in trealla_run_query (self=0x7227030, 
    src=0x7310470 "main") at src/trealla.c:2975
#6  0x000000000040d76e in trealla_consult_file (self=0x7227030, 
    name=0x7ffd46a3147e "../foo.pl") at src/trealla.c:2876
#7  0x00000000004044b5 in main (ac=3, av=0x7ffd46a2f9e8) at tpl.c:320
(gdb) 
```

**Comment by infradig** [comment]
Hmm, -O0 it's fine.

**Comment by infradig** [comment]
Ok, it's fixed, but has highlighted optimization (such as there is) needs work.
