### ISSUE TITLE
`foo(div).` cause segmentation fault

### ISSUE THREAD

**Issue by dram** [trealla-lang/trealla#93]
Following code will cause segmentation fault for Trealla:

```
foo(div).
```

Output:

```
Trealla v0.1alpha, 64-bits (int=128-bits), Jan 28 2017
ERROR: unexpected end of clause, line 1
ERROR: consult 'foo.pro', line=1, 'foo(div).'
INFO: consulted 'foo.pro': 7 terms
Segmentation fault (core dumped)
```

Backtrace:

```
Core was generated by `tpl foo.pro'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043822e in sl_app (d=0x680dd68, key=0x680a9d0 "div", value=0x680dd60) at src/skiplist.c:106
106                     while ((q = p->forward[k]) && (d->compare(q->key, key) <= 0))
(gdb) bt
#0  0x000000000043822e in sl_app (d=0x680dd68, key=0x680a9d0 "div", value=0x680dd60) at src/skiplist.c:106
#1  0x0000000000405a79 in assert_index (l=0x7ffce95db470, n=0x680dd60, manual=0, persist=0x7ffce95db40c, append_mode=1) at src/trealla.c:220
#2  0x0000000000405b36 in assertz_index (l=0x7ffce95db470, n=0x680dd60, manual=0, persist=0x7ffce95db40c) at src/trealla.c:233
#3  0x0000000000406eba in add_clauses (l=0x7ffce95db470, internal=0) at src/trealla.c:644
#4  0x0000000000408ce3 in trealla_consult_file (self=0x67fe010, filename=0x7ffce95dcd41 "foo.pro") at src/trealla.c:1217
#5  0x0000000000404849 in main (ac=2, av=0x7ffce95dc3b8) at tpl.c:325
```

**Comment by infradig** [comment]
I suppose because 'div' is an operator...

**Comment by dram** [comment]
Yes, I also think that's the cause.
